---
# handlers file for docker.ubuntu
- name: Start Docker
  service: name=docker state=started

- name: Reload systemd
  command: systemctl daemon-reload  

- name: Restart docker
  service: name=docker state=restarted
  when: docker_restart_permitted

- name: Restart dockerio
  service: name=docker.io state=restarted
  when: docker_restart_permitted
